//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArbeitsPlanung3_Lib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArbeitsPlanung3_ModelContainer : DbContext
    {
        public ArbeitsPlanung3_ModelContainer()
            : base("name=ArbeitsPlanung3_ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arbeiten> ArbeitenSet { get; set; }
        public virtual DbSet<Benutzer> BenutzerSet { get; set; }
        public virtual DbSet<Flugzeuge> FlugzeugeSet { get; set; }
    }
}
